version: '3'
services:
  
  mongo-db:
    image: mongo
    ports:
      - "27018:27017"
    container_name: mongo-db
    volumes:
      - ./db/:/data/db

  todo:
    build:
      dockerfile: Dockerfile
      context: ./todo
    container_name: todo
    ports:
      - "8002:8002"
    restart: always
    depends_on:
      - "mongo-db"
    volumes:
      - .:/app
      - /app/todo/node_modules

  user:
    build:
      dockerfile: Dockerfile
      context: ./user
    container_name: user
    ports:
      - "8001:8001"
    restart: always
    depends_on:
      - "mongo-db"
    volumes:
      - .:/app
      - /app/user/node_modules

  gateway:
    build:
      dockerfile: Dockerfile
      context: ./gateway
    depends_on:
      - todo
      - user
    ports:
      - "8000:8000"